attestation-derivation: curl --trace-ascii; request headers AS SENT
send-header-block 1 of 1
GET /fineract-provider/api/v1/offices HTTP/1.1
Host: localhost:8443
User-Agent: curl/8.7.1
Accept: */*
Authorization: Basic <redacted sha256:2614d66f727c25bb>
Fineract-Platform-TenantId: default
X-T274-Cmp: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
request-headers-artefact: cmp.reqhdr
request-headers-sha256: daf513a94e87f8428c8b8b3c1fad82402f7128a3e21475962bbc9751c60d08b4
body: <none>
captured-at-utc: 2026-08-22T14:27:24Z
