attestation-derivation: curl --trace-ascii; request headers AS SENT
attestation-schema: 2
send-header-block 1 of 1
GET /fineract-provider/api/v1/offices HTTP/1.1
Host: localhost:8443
User-Agent: curl/8.7.1
Accept: */*
Authorization: Basic <redacted sha256:2614d66f727c25bb>
Fineract-Platform-TenantId: default
X-T274-Cmp: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
request-headers-artefact: cmp.reqhdr
request-headers-sha256: daf513a94e87f8428c8b8b3c1fad82402f7128a3e21475962bbc9751c60d08b4
body: <none>
response-headers-artefact: cmp.resphdr
response-headers-sha256: dc5bb88696d825e65c4b563b193a7b264e06fa43f2e198d63e1be9dedab0889c
response-status-line: HTTP/1.1 200
response-artefact: cmp.json
response-sha256: ab2f53e6ca5572da6bcdeb71cdf026d571afa3311780040d642ce3b94696d0f4
response-bytes: 264
response-content-length-crosscheck: MATCH (264 bytes)
response-status-crosscheck: MATCH (200)
response-status-artefact: cmp.status
captured-at-utc: 2026-08-22T14:27:24Z
