#!/usr/bin/env python3
"""T47 edit 1 - §4.1.1 step B: pin the packed rule, replace 'not yet captured'
with the T46 non-separability proof.  Idempotent: refuses to run twice."""
import io
import os
import sys

W = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
DOC = os.path.join(W, "docs/adr/DEC-1-schedule-generator-adapter.md")

s = io.open(DOC, encoding="utf-8").read()


def rep(old, new):
    global s
    n = s.count(old)
    if n != 1:
        sys.exit("edit1: expected 1 occurrence, found %d for: %.90s" % (n, old))
    s = s.replace(old, new)


# ---------------------------------------------------------------- 1a
rep(
    "**A port must implement the packed rule WITH the special case, or the "
    "clamped-step rule WITHOUT it; taking the packed rule and dropping the "
    "special case double-charges alternate periods, and that combination is "
    "the one a careless port lands on.**",

    "**Revision 10 PINS the packed rule as this document's normative reading of "
    "`k`, together with the special case** — the pin is stated normatively at "
    "the end of the next paragraph, and what forced it is that task T46 **proved** "
    "the two clauses are not separable by any capture on any arm of this routine. "
    "Taking the packed rule and **dropping** the special case double-charges "
    "alternate periods, and that combination is the one a careless port lands on. "
    "(This document calls the other whole-months function the **clamped-step** "
    "rule; task T46 calls the same function **naive**. One function, two names; no "
    "claim below turns on which is used.)")

# ---------------------------------------------------------------- 1b
old282 = (
    "**What that does NOT show, and revision 9 states it because the difference "
    "decides what a vector is worth.** The refuted reading is `packed rule ∧ no "
    "special case`. It is **not** the reading a careless porter most naturally "
    "writes, which is `clamped-step rule ∧ no special case` — and that one is "
    "**indistinguishable from the oracle** on this whole family and far beyond it. "
    "Task T44 measured it: over **59,130** `(ScheduleStartDate, repayment period)` "
    "pairs across 1,095 start dates in 2023–2025 × terms {6, 12, 36}, "
    "`RepaymentEvery` 1, MONTHS, the special case fires on **701** periods, the "
    "packed and clamped-step whole-months functions disagree on **exactly those "
    "same 701**, and the two whole readings differ on **0** [VERIFIED: "
    "`.softhouse/capture/audit-t44/analysis/t44_r2_vs_r4_sweep-output.txt`; **and "
    "re-derived independently by task T45 inside this document's own from-text "
    "model**, reproducing T44's 59,130 / 701 / 701 / 0 digit for digit — "
    "`.softhouse/reviews/t45-probe/t45-extra-output.txt`, leg C3]. **One trap worth "
    "recording, because it is what makes this measurement easy to get wrong:** the "
    "sweep must build its boundaries with §4.2's **re-anchor**, not with plain "
    "`plusMonths`. On plain `plusMonths` boundaries the special case fires **zero** "
    "times over the same 59,130 pairs and the sweep silently proves nothing — "
    "T45's first run did exactly that. **The special case is precisely a "
    "compensation for the packed rule's month-end undercount, and the two errors "
    "cancel on every input.** This is F-1's ambiguity, measured — and it is why "
    "step B pins the pair rather than either clause, and why §8 item **3f** grades "
    "the **pair** and not the special case alone.")

assert s.count(old282) == 1, "edit1b anchor not found / not unique"

new282 = (
    "**What that does NOT show — and revision 10 replaces revision 9's \"not yet "
    "captured\" with \"NOT CAPTURABLE\", because task T46 proved it.** The refuted "
    "reading is `packed ∧ no special case`. It is **not** the reading a careless "
    "porter most naturally writes, which is `clamped-step ∧ no special case` — "
    "and that one is not merely uncaptured. It is **observationally identical to "
    "the oracle on every input**, and **no capture on any arm of "
    "`calculatePeriodRatio` can ever separate the special case by itself.** That is "
    "a stronger and a different statement from revision 9's, and it is carried by "
    "**three kinds of evidence, which revision 10 keeps distinct rather than "
    "flattening into one word.**\n"
    "\n"
    "**(i) A closed form — a RE-DERIVATION, performed independently by this task "
    "from [`ProgressiveEMICalculator.java:1419-1459`] and [`DateUtils.java:308-317`] "
    "and agreeing with T46's.** Write `pm(d) = d.year × 12 + d.month` for the "
    "proleptic month, `k = pm(b) − pm(a)`, and `len(b)` for the length of `b`'s "
    "month. At every reachable call site `a ≤ b`, because the seed is either "
    "`ScheduleStartDate` — the **first** repayment period's `FromDate` "
    "[`ProgressiveLoanInterestScheduleModel.java:209-211`] — or this period's own "
    "`FromDate` [`:1477-1480`]. Then, for `k ≥ 1`:\n"
    "\n"
    "```\n"
    "packed(a, b) = k − [a.day > b.day]                       # ChronoUnit.MONTHS.between, :1435\n"
    "clamped(a, b) = k − [min(a.day, len(b)) > b.day]         # largest j with a.plusMonths(j) <= b\n"
    "\n"
    "packed(a, b) != clamped(a, b)  <=>  b.day == len(b)  AND  a.day > b.day\n"
    "```\n"
    "\n"
    "**The right-hand side is verbatim the predicate at [`:1432`]** — "
    "`targetDateLastDay == targetDateDay && seedDateDay > targetDateDay`. The "
    "equivalence is exact: `min(a.day, len(b)) > b.day` implies `a.day > b.day`, so "
    "the two indicators can differ only when `a.day > b.day` **and** "
    "`min(a.day, len(b)) ≤ b.day`; given the first conjunct the second forces "
    "`len(b) ≤ b.day`, and `b.day ≤ len(b)` always, so `b.day = len(b)`. When they "
    "differ, `packed` is one **less** than `clamped`. **And when the predicate "
    "fires the oracle measures to `FromDate.plusDays(1)` [`:1433`]**, which is the "
    "**1st** of the next month: `pm` rises by one, and the predicate itself forces "
    "`a.day > b.day = len(b) ≥ 28`, so `a.day ≥ 29 > 1` and "
    "`packed(a, b+1 day) = (k+1) − 1 = k = clamped(a, b)`. **Therefore "
    "`k_oracle ≡ k_clamped`, identically, on the whole reachable domain: the "
    "special case IS the compensation for the packed rule's month-end undercount, "
    "and neither clause is separately observable.** *(One boundary this task "
    "re-derived and T46 did not state: at `k = 0` Java's truncation-toward-zero "
    "makes `packed = 0` where the floor form would give `−1`. It is unreachable "
    "here — `a ≤ b` with `pm(a) = pm(b)` forces `a.day ≤ b.day`, so neither the "
    "predicate at [`:1432`] nor the divergence above can fire. Recorded because a "
    "port that transcribes the closed form instead of `MONTHS.between` must "
    "reproduce the truncation, not a floor.)*\n"
    "\n"
    "**(ii) An EXHAUSTIVE MEASUREMENT inside the pinned oracle image — an "
    "observation of the oracle JVM's own `java.time`, and neither a re-derivation "
    "nor a capture of loan money** [VERIFIED: task T46, "
    "`.softhouse/capture/periodratio/analysis/T46MonthDiffExhaustive.java`, output "
    "`analysis/t46_monthdiff_exhaustive-output.txt`, compiled and run in a throwaway "
    "container on the pinned image, `java.vm.version 21.0.11+10-LTS`]. Over **every** "
    "ordered pair `a ≤ b` of civil dates in 2000-01-01 … 2040-12-31:\n"
    "\n"
    "| quantity | count |\n"
    "|---|---|\n"
    "| ordered date pairs swept | **112,147,776** |\n"
    "| the [`:1432`] predicate FIRES | **45,253** |\n"
    "| `packed ≠ clamped` | **45,253** |\n"
    "| fires **and** `packed == clamped` | **0** |\n"
    "| does not fire **and** `packed ≠ clamped` | **0** |\n"
    "| `k_oracle ≠ k_clamped` | **0** |\n"
    "| `k_oracle ≠ k_packed` | **45,253** |\n"
    "\n"
    "T44's earlier sweep is a **subset of this one by construction**: over **59,130** "
    "`(ScheduleStartDate, repayment period)` pairs across 1,095 start dates in "
    "2023–2025 × terms {6, 12, 36}, `RepaymentEvery` 1, MONTHS, the special case "
    "fires on **701** periods, the two whole-months functions disagree on **exactly "
    "those same 701**, and the two whole readings differ on **0** [VERIFIED: "
    "`.softhouse/capture/audit-t44/analysis/t44_r2_vs_r4_sweep-output.txt`; **and "
    "re-derived independently by task T45 inside this document's own from-text "
    "model**, reproducing T44's 59,130 / 701 / 701 / 0 digit for digit — "
    "`.softhouse/reviews/t45-probe/t45-extra-output.txt`, leg C3; **and both figure "
    "sets re-derived a third time from this document's own text by task T47**, "
    "`.softhouse/reviews/t47-probe/t47-monthend-output.txt`]. **One trap worth "
    "recording, because it is what makes the 59,130-pair form of this measurement "
    "easy to get wrong:** that sweep must build its boundaries with §4.2's "
    "**re-anchor**, not with plain `plusMonths`. On plain `plusMonths` boundaries "
    "the special case fires **zero** times over the same 59,130 pairs and the sweep "
    "silently proves nothing — T45's first run did exactly that. The "
    "112,147,776-pair form has no such trap, because it sweeps date pairs directly "
    "and builds no schedule.\n"
    "\n"
    "**(iii) The escape route revision 9 named is CLOSED, and closed by an "
    "observation rather than by an argument.** Revision 9 wrote that a "
    "discriminator for the special case alone \"must come from "
    "`calculatePeriodRatio`'s `YEARS` / `WEEKS` / `DAYS` arms\" [`:1405`, `:1407`, "
    "`:1408`] and recorded the item as `TO_BE_CAPTURED`. Task T46 captured all "
    "three arms and none of them delivers one. **`WEEKS` and `DAYS` cannot separate "
    "the two rules at all**: `seed.plus(k, WEEKS)` is `+7k` days and "
    "`seed.plus(k, DAYS)` is `+k` days, so nothing ever clamps and the packed and "
    "clamped-step functions coincide identically — measured **0** separations in "
    "the same 112,147,776-pair sweep. **`YEARS` does separate — on 165 pairs, every "
    "one a 29 February seed against a 28 February target — but the `YEARS` arm is "
    "UNREACHABLE.** `calculatePeriodRatio` computes the `YEARS` ratio at [`:1405`] "
    "and the result is handed to "
    "`calculateRateFactorPerPeriodBasedOnRepaymentFrequency` [`:1598-1610`], whose "
    "`switch` carries arms for `DAYS`, `WEEKS` and `MONTHS` and "
    "`default -> throw new UnsupportedOperationException(\"Invalid repayment frequency\")` "
    "at [`:1609`] [VERIFIED: `:1598-1610` re-opened in the pinned checkout by this "
    "task]. *Observed*: both `T46-YR-A` (the 29 February separator shape) and "
    "`T46-YR-B` (an ordinary seed) return "
    "`java.lang.UnsupportedOperationException: Invalid repayment frequency` "
    "[VERIFIED: task T46, `.softhouse/capture/periodratio/out/t46-periodratio-arms.json`]. "
    "**So the last place a separating shape could have lived returns no schedule at "
    "all.**\n"
    "\n"
    "**Consequence, NORMATIVE — and this is what revision 10 changes in this "
    "subsection.** Of the four combinations of the two clauses, **exactly one is "
    "wrong**:\n"
    "\n"
    "| whole-months rule | month-end special case | agrees with the oracle? |\n"
    "|---|---|---|\n"
    "| **packed** [`:1435`] | **present** [`:1426-1436`] | **YES — this IS the oracle, and it is what this document pins** |\n"
    "| clamped-step | absent | YES — identical on all 112,147,776 swept pairs |\n"
    "| clamped-step | present | YES — the case is inert on top of the clamped-step rule, since it yields `k` either way |\n"
    "| **packed** | **absent** | **NO — diverges on 45,253 of 112,147,776 pairs; refuted on 116 of 116 discriminating cells** |\n"
    "\n"
    "**This document specifies the oracle's own two clauses — packed `k` WITH the "
    "special case — and a port must implement that pair.** A port that implements "
    "the clamped-step rule with no special case is conformant, and revision 10 says "
    "so plainly rather than leaving the reader to infer it; but the pinned reading "
    "is the packed pair, because a specification that names the compensation without "
    "naming the thing it compensates for is one careless edit away from the only "
    "wrong combination in the table. **A blind spot that is proved UNCLOSABLE is a "
    "different fact from one that is merely uncaptured, and a `TO_BE_CAPTURED` that "
    "can never succeed is a defect in this document — which is why §8 item 3f no "
    "longer carries one.** §8 item **3f** therefore grades the **pair** and states "
    "that separating the special case alone is impossible; §9 obligation (f) pins "
    "the pair; and the honest statement about the seven witnesses is that a port "
    "with two cancelling defects passes them **and is correct on this arm**, which "
    "is a better outcome than an open vector request that could never be filled.")

s = s.replace(old282, new282)

io.open(DOC, "w", encoding="utf-8").write(s)
print("edit1: ok")
