#!/usr/bin/env python3
"""T326 -- regenerate `.softhouse/guards/dead-path-frontier.pin` from a census JSON.

THE PIN IS DERIVED, NEVER TYPED. This script reads the census's machine-readable output and
writes the pin's header verbatim plus one row per (instrument | dead literal). It refuses to
write an empty body, because an empty pin is a failed read and the guard treats it as one.

USAGE
    python3 .../10-regen-pin.py --census <census.json> [--check]

`--check` writes nothing and exits 1 if the pin on disk differs from what would be written --
that is how the cross-host proof compares two conditions without touching the tree.

EXIT: 0 written/identical; 1 --check found a difference; 2 refusal (bad input, empty body).
"""
import argparse
import json
import sys
from pathlib import Path

HEADER = """\
# T316 -- THE DEAD-PATH FRONTIER PIN.   (resolution rebuilt by T326)
#
# One row per (tracked .softhouse/ instrument | repo-relative path literal it names that IS NOT
# IN THE TRACKED UNIVERSE). DERIVED by
# `.softhouse/capture/t316-dead-path-guards/census_dead_paths.py`, regenerated by
# `.softhouse/capture/t326-frontier-host-state/instruments/10-regen-pin.py`, NEVER TYPED.
# Enforced by `.softhouse/guards/check-dead-path-frontier.sh`.
#
# ===========================================================================================
# T326 -- WHAT "DOES NOT RESOLVE" MEANS, AND WHY IT NO LONGER MEANS "IS NOT ON THIS DISK".
# ===========================================================================================
# T316 resolved literals with `os.path.exists()`. The driver of fire 20260827-230001 merged the
# HARD wiring locally and ran the bar; it came back EXIT 2 with ZERO probe lines --
#
#     T316-DEADPATH-FRONTIER: REFUSED rows=78 pinned=98 added=4 removed=24
#
# -- and under P-84 ("'EXIT 2 WITH NO PROBE LINE' IS THE GUARD WORKING. READ THE ABSENCE, NOT
# THE VALUE") that is a FAILED HARD GUARD, not an oracle outage. The guard was right to refuse.
# THE PIN WAS THE DEFECT. Measured cause, reproduced by T326 on ONE commit on ONE host:
#
#     .softhouse/toolchain                       `.gitignore:6`, ZERO tracked files, present in
#                                                Buyan's main checkout, absent in every worktree
#                                                -> 23 rows
#     .softhouse/capture/t74-multiplesof/
#         T82-guard-proofs/scratch               untracked RUN RESIDUE from an earlier run,
#                                                present in the main checkout only  -> 1 row
#
#     frontier in a fresh worktree : rows=102
#     frontier in the main checkout: rows= 78      SAME COMMIT.
#
# So the second class is not even "a different machine" -- it is "the same machine after a run
# that left something behind". A guard wired HARD on that makes the bar's colour a property of
# run history. This program is driven by TWO fires (a launchd fire on Buyan's Mac and a cloud
# fire that never runs on that host); T256/T298 established that no graded path may depend on
# where it runs, and `guard_no_host_state_in_lint_corpus` already exists for this class.
#
# THE RULE: if regenerating a pin in a worktree, on a fresh clone, or on another host yields a
# different set, IT IS NOT A PIN -- it is a snapshot of somebody's disk.
#
# -------------------------------------------------------------------------------------------
# THE DECISION, ARGUED: AN UNTRACKED-BUT-EXPECTED PATH IS **DEAD**.
# -------------------------------------------------------------------------------------------
# `.softhouse/toolchain` is real, is used, and is DELIBERATELY untracked (`.gitignore:6`). It is
# named by 20 distinct tracked instruments in 25 of the rows below, counted from this file:
#     grep -v '^#' dead-path-frontier.pin | grep -c toolchain              -> 25
#     grep -v '^#' dead-path-frontier.pin | grep toolchain | cut -d'|' -f1 | sort -u | wc -l -> 20
# (23 of those rows are the ones the driver watched vanish; the other 2 are T326's own drives,
# which name the path deliberately -- see the accounting below.) Three answers were available:
#
#   (a) RESOLVES, because it exists.        REJECTED -- that is the defect verbatim. It requires
#       looking at the disk, so it answers differently in a worktree and in the main checkout.
#
#   (b) RESOLVES, via an allowlist of "untracked but expected" prefixes.   REJECTED, and this is
#       the one worth arguing because it looks reasonable. It IS host-stable, so it passes the
#       stated test -- but it is stable by ASSERTING liveness that nothing in the commit backs.
#       On the cloud fire, which never unpacks a toolchain, the allowlist would say a path
#       resolves that is not there. That is P-22 -- "a guard, a canary, or a control that CANNOT
#       FAIL is worse than none, because it is believed". It also converts the frontier from a
#       derived measurement into a hand-maintained amnesty, which is the exact thing the block
#       in conformance.sh headed THE PIN IS A FRONTIER, NOT AN AMNESTY forbids ("A '+' row is
#       a NEW site: repair it ... rather than pinning it"). GREP THAT SENTENCE, not a line
#       number: it was cited as :1715 and T326 measured it at :1727 -- stale by 12 before this
#       pin existed (P-86).
#
#   (c) DEAD, always, present or not.       CHOSEN. From the commit alone, nothing establishes
#       that `.softhouse/toolchain` exists; a reference to it is a reference to something the
#       repository does not contain. That is exactly what this census's DEAD bucket has always
#       meant -- and T316 wrote the meaning down before this question arose: a row is "a SMELL
#       that must be inspected once, by a human, and then either repaired or pinned with its
#       reason. This guard COUNTS; it does not judge." A materialised-at-runtime toolchain is a
#       row inspected once, pinned here, WITH ITS REASON. It gives the SAME ANSWER WITH AND
#       WITHOUT THE DIRECTORY PRESENT, which was the whole test.
#
# THE ROWS THIS DECISION KEEPS ARE THEREFORE PINNED ON PURPOSE, not overlooked. They are the
# `.softhouse/toolchain*` rows and the T82 `scratch` rows: correct references to paths that are
# generated at runtime and will never be tracked.
#
# -------------------------------------------------------------------------------------------
# THE ROWS FOLDED IN BY T326, EACH INSPECTED. The pin moved from 98 rows to 109.
# -------------------------------------------------------------------------------------------
# +4  T305's red drive `red-drive-conformance-guard.sh`. Carried since T323 in
#     `DEADPATH_T323_RECONCILE_LIST` in conformance.sh because the pin was outside T323's edit
#     grant; that list is EMPTIED in the same commit that adds these, so nothing is excused
#     twice. T323 inspected all four and they are paths the drive CREATES at run time inside a
#     throwaway clone -- two ledger vectors it writes, and an `attest` dir under the
#     deliberately fictional task id `t999-rig`. A red drive plants files that MUST NOT exist in
#     a clean tree; that is what makes it a red drive.
#
# +4  T326's own two drives -- `20-cross-host-drive.sh` and `30-bar-in-both-conditions.sh`, two
#     rows each -- which name the toolchain path and the T82 residue path. FUNCTIONAL by T323's
#     test -- "CAN THE INSTRUMENT STILL DO ITS JOB IF THE LITERAL GOES AWAY?" -- and the answer
#     is no, unusually clearly: each drive's entire job is to MATERIALISE THOSE TWO EXACT PATHS,
#     because they are the 24 rows the driver measured. Assembling them at run time from
#     fragments would make the drives stop testing the thing they exist to test, which is the
#     "defeating the instrument to flatter its own number" that T323 warned about.
#
#     NOTE THE PROPERTY THIS DEPENDS ON. Under the OLD resolver these drives would have perturbed
#     the frontier they were measuring -- exactly T323's case (b), where its own red drive's
#     sibling arm created a directory and three rows vanished mid-run. Under the tracked resolver
#     they provably cannot: creating an untracked directory changes nothing the census reads.
#     `20-cross-host-drive.sh` measures that fact and would fail if it stopped holding.
#
# -0  Nothing was removed. The 24 host-dependent rows STAY, by the decision above, and they now
#     stay in every condition rather than in some of them.
#
# +1  `.softhouse/reviews/T306/probe/inject-acceptance.py |
#      .softhouse/vectors/ledger/ZZZ-T306-INJECTED-preclosure-acceptance.json`
#     ARRIVED ON `main` WHILE T326 WAS RUNNING, in T306's merge, and THE GUARD CAUGHT IT ON THE
#     FIRST BAR AFTER THE MERGE -- `REFUSED rows=107 pinned=106 added=1 removed=0`. That is the
#     wired guard doing the job it was wired for, on a site nobody had told it about. It was
#     INSPECTED ONCE, BY A HUMAN-EQUIVALENT READ OF THE SOURCE, before being pinned:
#
#       * the literal is joined onto `scratch`, which is `pathlib.Path(sys.argv[1]).resolve()`
#         and is REQUIRED to be under `tempfile.gettempdir()` -- the script exits with
#         "REFUSING to write" otherwise. So it is a path the probe CREATES AT RUN TIME inside a
#         throwaway copy of the vector store, and it MUST NOT exist in the repo: the probe
#         injects a deliberately-wrong vector, and a committed copy of that would be a poisoned
#         store.
#       * FUNCTIONAL by T323's test -- "CAN THE INSTRUMENT STILL DO ITS JOB IF THE LITERAL GOES
#         AWAY?" -- no: it is the file the probe writes; without it the probe writes nothing.
#       * SAME CLASS, byte for byte, as the four T305 rows above. Pinning it is the disposition
#         T316's own header prescribes: "a SMELL that must be inspected once, by a human, and
#         then either repaired or pinned WITH ITS REASON."
#       * REPAIR WAS CONSIDERED AND IS NOT AVAILABLE. "Make the path resolve" means committing
#         `ZZZ-T306-INJECTED-preclosure-acceptance.json` into `.softhouse/vectors/ledger/`,
#         which would put a deliberately-wrong acceptance vector into the graded store. The
#         other literal in the same file --
#         `.softhouse/vectors/ledger/LDG-04-header-account-accepted.json` -- RESOLVES, which is
#         why only one row arrived rather than two, and is the control that shows the census is
#         reading this file correctly.
#       * HOST-STABLE: the target is never tracked on any host, in any condition, because the
#         script refuses to write it into a repo at all. Re-proved by the cross-host drive at
#         107 rows in all four disk conditions.
#     T306's file is NOT EDITED here: T306 is another worker's partition and the row is correct
#     as written. Filed as FU-T326-7 so the next holder of that file knows the row exists.
#
# +2  `.softhouse/capture/t272-goenv-graft/instruments/20-strict-drive.sh | .softhouse/toolchain`
#     and `.../60-cloud-f3-reproduction.sh | .softhouse/toolchain`, arriving in T272's merge --
#     the THIRD time `main` moved under T326 and the SECOND time the wired guard caught a site
#     nobody had told it about. Both are the STANDING toolchain class: T272's whole subject is
#     the Go-toolchain graft, so of course its drives name `.softhouse/toolchain`, and 20 other
#     tracked instruments already carry that same row for the same reason. Pinned under the
#     decision at the top of this header -- an untracked-but-expected path is DEAD, present or
#     not -- which is exactly why these two rows are STABLE: they are dead on Buyan's Mac with
#     the toolchain unpacked and dead on the cloud fire without it.
#
# +0/-1 A THIRD ROW ARRIVED IN THE SAME MERGE AND WAS REPAIRED RATHER THAN PINNED:
#     `.softhouse/capture/t272-goenv-graft/instruments/10-locate-cloud-arm.sh` names
#     `...t254-harness-portability/REVIEW.md:36-44)` inside a prose `echo`. THE FILE IS TRACKED;
#     what the census could not see past was a LINE-RANGE CITATION -- the same P-86 shape T326
#     spent its day repairing. The guard's printed rule is "a '+' row is a NEW site: REPAIR it
#     rather than pinning it", and pinning a false positive is how a census decays into the
#     wolf-crier its own header warns about. So the SELECTOR was repaired (`CITATION_RE` in
#     census_dead_paths.py, an arm consulted only after the others fail and only ever to say
#     YES) and no row was added. Measured delta of that repair, end to end: deadFiles 77 -> 76,
#     resolving 1072 -> 1073, and NOTHING ELSE MOVED.
#
#     ITS OWN FIRST DRAFT ADDED A ROW AND THE GUARD CAUGHT IT ON THE NEXT RUN. The comment
#     explaining the arm quoted the frontier's `PIN.json` row as a control, and this census
#     counts quoted literals, so the explanation became an instrument naming a dead path. The
#     quotation was removed rather than the row pinned. That is the third time in this file's
#     history that the frontier guard has caught the very commit that touches it (T323's wiring
#     quotations, T306's probe, this comment), and it is the strongest argument on record that
#     wiring it HARD was right.
#
# -------------------------------------------------------------------------------------------
# A ROW IS NOT AN ACCUSATION. It records that an instrument names a path the repository does not
# contain. That may be a defect (a required input that will never resolve, silently skipped) or
# entirely correct (a fallback candidate, an output about to be created, a runtime toolchain, a
# docstring example). T316 measured the two rows FU-T299-2 named -- guard_rvpa_floor_t290.py and
# red/drive-red-t290.py -- and both are CORRECT: the literal is candidate #1 of an ordered
# two-candidate list whose second candidate resolves, and when neither resolves both exit 2 with
# the probe line absent.
#
# THIS IS A FRONTIER, NOT AN AMNESTY (conformance.sh -- grep that sentence; the line moves and
# the cardinal :1715 was already stale by 12). A NEW row must be REPAIRED, not
# pinned. A row that disappears is good news and must be deleted here IN THE SAME COMMIT, or the
# pin starts excusing a weakness that is no longer there.
#
# Blank lines and `#` comments are ignored by the guard.
"""


def rows_from(census_path: Path):
    try:
        doc = json.loads(census_path.read_text())
    except (OSError, ValueError) as exc:
        print("ERROR: could not read census JSON %s: %s" % (census_path, exc), file=sys.stderr)
        raise SystemExit(2)
    for key in ("deadFiles", "perFile"):
        if key not in doc:
            print("ERROR: census JSON has no %r key. REFUSING (exit 2)." % key, file=sys.stderr)
            raise SystemExit(2)
    rows = set()
    for f in doc["deadFiles"]:
        for d in doc["perFile"][f]["dead"]:
            rows.add("%s | %s" % (f, d))
    if not rows:
        print("ERROR: the census reports ZERO dead rows. A pin body of zero rows is a failed",
              file=sys.stderr)
        print("ERROR: read, not an empty frontier -- the guard refuses on it. REFUSING (exit 2).",
              file=sys.stderr)
        raise SystemExit(2)
    return sorted(rows)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="regenerate the T316 dead-path frontier pin")
    ap.add_argument("--census", required=True, help="census JSON produced by --json")
    ap.add_argument("--pin", default=None, help="pin file (default: the repo's)")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if the pin differs from the derived content")
    args = ap.parse_args(argv)

    here = Path(__file__).resolve()
    root = here.parents[3].parent  # .../.softhouse/capture/t326-.../instruments/ -> repo root
    pin = Path(args.pin) if args.pin else root / ".softhouse/guards/dead-path-frontier.pin"

    body = HEADER + "\n".join(rows_from(Path(args.census))) + "\n"

    if args.check:
        if not pin.exists():
            print("DIFFERS: %s does not exist" % pin)
            return 1
        if pin.read_text() == body:
            print("IDENTICAL: %s matches the derived content" % pin)
            return 0
        print("DIFFERS: %s does not match the derived content" % pin)
        return 1

    pin.parent.mkdir(parents=True, exist_ok=True)
    pin.write_text(body)
    print("wrote %d row(s) to %s" % (body.count("\n") - HEADER.count("\n"), pin))
    return 0


if __name__ == "__main__":
    sys.exit(main())
