#!/usr/bin/env python3
"""T326 -- regenerate `.softhouse/guards/dead-path-frontier.pin` from a census JSON.

THE PIN IS DERIVED, NEVER TYPED. This script reads the census's machine-readable output and
writes the pin's header verbatim plus one row per (instrument | dead literal). It refuses to
write an empty body, because an empty pin is a failed read and the guard treats it as one.

USAGE
    python3 .../10-regen-pin.py --census <census.json> [--check]

`--check` writes nothing and exits 1 if the pin on disk differs from what would be written --
that is how the cross-host proof compares two conditions without touching the tree.

EXIT: 0 written/identical; 1 --check found a difference; 2 refusal (bad input, empty body).
"""
import argparse
import json
import sys
from pathlib import Path

HEADER = """\
# T316 -- THE DEAD-PATH FRONTIER PIN.   (resolution rebuilt by T326)
#
# One row per (tracked .softhouse/ instrument | repo-relative path literal it names that IS NOT
# IN THE TRACKED UNIVERSE). DERIVED by
# `.softhouse/capture/t316-dead-path-guards/census_dead_paths.py`, regenerated by
# `.softhouse/capture/t326-frontier-host-state/instruments/10-regen-pin.py`, NEVER TYPED.
# Enforced by `.softhouse/guards/check-dead-path-frontier.sh`.
#
# ===========================================================================================
# T326 -- WHAT "DOES NOT RESOLVE" MEANS, AND WHY IT NO LONGER MEANS "IS NOT ON THIS DISK".
# ===========================================================================================
# T316 resolved literals with `os.path.exists()`. The driver of fire 20260827-230001 merged the
# HARD wiring locally and ran the bar; it came back EXIT 2 with ZERO probe lines --
#
#     T316-DEADPATH-FRONTIER: REFUSED rows=78 pinned=98 added=4 removed=24
#
# -- and under P-84 ("'EXIT 2 WITH NO PROBE LINE' IS THE GUARD WORKING. READ THE ABSENCE, NOT
# THE VALUE") that is a FAILED HARD GUARD, not an oracle outage. The guard was right to refuse.
# THE PIN WAS THE DEFECT. Measured cause, reproduced by T326 on ONE commit on ONE host:
#
#     .softhouse/toolchain                       `.gitignore:6`, ZERO tracked files, present in
#                                                Buyan's main checkout, absent in every worktree
#                                                -> 23 rows
#     .softhouse/capture/t74-multiplesof/
#         T82-guard-proofs/scratch               untracked RUN RESIDUE from an earlier run,
#                                                present in the main checkout only  -> 1 row
#
#     frontier in a fresh worktree : rows=102
#     frontier in the main checkout: rows= 78      SAME COMMIT.
#
# So the second class is not even "a different machine" -- it is "the same machine after a run
# that left something behind". A guard wired HARD on that makes the bar's colour a property of
# run history. This program is driven by TWO fires (a launchd fire on Buyan's Mac and a cloud
# fire that never runs on that host); T256/T298 established that no graded path may depend on
# where it runs, and `guard_no_host_state_in_lint_corpus` already exists for this class.
#
# THE RULE: if regenerating a pin in a worktree, on a fresh clone, or on another host yields a
# different set, IT IS NOT A PIN -- it is a snapshot of somebody's disk.
#
# -------------------------------------------------------------------------------------------
# THE DECISION, ARGUED: AN UNTRACKED-BUT-EXPECTED PATH IS **DEAD**.
# -------------------------------------------------------------------------------------------
# `.softhouse/toolchain` is real, is used by `.softhouse/bin/go-env.sh` and 20 other
# instruments, and is DELIBERATELY untracked (`.gitignore:6`). Three answers were available:
#
#   (a) RESOLVES, because it exists.        REJECTED -- that is the defect verbatim. It requires
#       looking at the disk, so it answers differently in a worktree and in the main checkout.
#
#   (b) RESOLVES, via an allowlist of "untracked but expected" prefixes.   REJECTED, and this is
#       the one worth arguing because it looks reasonable. It IS host-stable, so it passes the
#       stated test -- but it is stable by ASSERTING liveness that nothing in the commit backs.
#       On the cloud fire, which never unpacks a toolchain, the allowlist would say a path
#       resolves that is not there. That is P-22 -- "a guard, a canary, or a control that CANNOT
#       FAIL is worse than none, because it is believed". It also converts the frontier from a
#       derived measurement into a hand-maintained amnesty, which is the exact thing
#       conformance.sh:1715 forbids ("A '+' row is a NEW site: repair it ... rather than
#       pinning it").
#
#   (c) DEAD, always, present or not.       CHOSEN. From the commit alone, nothing establishes
#       that `.softhouse/toolchain` exists; a reference to it is a reference to something the
#       repository does not contain. That is exactly what this census's DEAD bucket has always
#       meant -- and T316 wrote the meaning down before this question arose: a row is "a SMELL
#       that must be inspected once, by a human, and then either repaired or pinned with its
#       reason. This guard COUNTS; it does not judge." A materialised-at-runtime toolchain is a
#       row inspected once, pinned here, WITH ITS REASON. It gives the SAME ANSWER WITH AND
#       WITHOUT THE DIRECTORY PRESENT, which was the whole test.
#
# THE ROWS THIS DECISION KEEPS ARE THEREFORE PINNED ON PURPOSE, not overlooked. They are the
# `.softhouse/toolchain*` rows and the T82 `scratch` rows: correct references to paths that are
# generated at runtime and will never be tracked.
#
# -------------------------------------------------------------------------------------------
# THE ROWS FOLDED IN BY T326, EACH INSPECTED. The pin moved from 98 rows to 106.
# -------------------------------------------------------------------------------------------
# +4  T305's red drive `red-drive-conformance-guard.sh`. Carried since T323 in
#     `DEADPATH_T323_RECONCILE_LIST` in conformance.sh because the pin was outside T323's edit
#     grant; that list is EMPTIED in the same commit that adds these, so nothing is excused
#     twice. T323 inspected all four and they are paths the drive CREATES at run time inside a
#     throwaway clone -- two ledger vectors it writes, and an `attest` dir under the
#     deliberately fictional task id `t999-rig`. A red drive plants files that MUST NOT exist in
#     a clean tree; that is what makes it a red drive.
#
# +4  T326's own two drives -- `20-cross-host-drive.sh` and `30-bar-in-both-conditions.sh`, two
#     rows each -- which name the toolchain path and the T82 residue path. FUNCTIONAL by T323's
#     test -- "CAN THE INSTRUMENT STILL DO ITS JOB IF THE LITERAL GOES AWAY?" -- and the answer
#     is no, unusually clearly: each drive's entire job is to MATERIALISE THOSE TWO EXACT PATHS,
#     because they are the 24 rows the driver measured. Assembling them at run time from
#     fragments would make the drives stop testing the thing they exist to test, which is the
#     "defeating the instrument to flatter its own number" that T323 warned about.
#
#     NOTE THE PROPERTY THIS DEPENDS ON. Under the OLD resolver these drives would have perturbed
#     the frontier they were measuring -- exactly T323's case (b), where its own red drive's
#     sibling arm created a directory and three rows vanished mid-run. Under the tracked resolver
#     they provably cannot: creating an untracked directory changes nothing the census reads.
#     `20-cross-host-drive.sh` measures that fact and would fail if it stopped holding.
#
# -0  Nothing was removed. The 24 host-dependent rows STAY, by the decision above, and they now
#     stay in every condition rather than in some of them.
#
# -------------------------------------------------------------------------------------------
# A ROW IS NOT AN ACCUSATION. It records that an instrument names a path the repository does not
# contain. That may be a defect (a required input that will never resolve, silently skipped) or
# entirely correct (a fallback candidate, an output about to be created, a runtime toolchain, a
# docstring example). T316 measured the two rows FU-T299-2 named -- guard_rvpa_floor_t290.py and
# red/drive-red-t290.py -- and both are CORRECT: the literal is candidate #1 of an ordered
# two-candidate list whose second candidate resolves, and when neither resolves both exit 2 with
# the probe line absent.
#
# THIS IS A FRONTIER, NOT AN AMNESTY (conformance.sh:1715). A NEW row must be REPAIRED, not
# pinned. A row that disappears is good news and must be deleted here IN THE SAME COMMIT, or the
# pin starts excusing a weakness that is no longer there.
#
# Blank lines and `#` comments are ignored by the guard.
"""


def rows_from(census_path: Path):
    try:
        doc = json.loads(census_path.read_text())
    except (OSError, ValueError) as exc:
        print("ERROR: could not read census JSON %s: %s" % (census_path, exc), file=sys.stderr)
        raise SystemExit(2)
    for key in ("deadFiles", "perFile"):
        if key not in doc:
            print("ERROR: census JSON has no %r key. REFUSING (exit 2)." % key, file=sys.stderr)
            raise SystemExit(2)
    rows = set()
    for f in doc["deadFiles"]:
        for d in doc["perFile"][f]["dead"]:
            rows.add("%s | %s" % (f, d))
    if not rows:
        print("ERROR: the census reports ZERO dead rows. A pin body of zero rows is a failed",
              file=sys.stderr)
        print("ERROR: read, not an empty frontier -- the guard refuses on it. REFUSING (exit 2).",
              file=sys.stderr)
        raise SystemExit(2)
    return sorted(rows)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="regenerate the T316 dead-path frontier pin")
    ap.add_argument("--census", required=True, help="census JSON produced by --json")
    ap.add_argument("--pin", default=None, help="pin file (default: the repo's)")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if the pin differs from the derived content")
    args = ap.parse_args(argv)

    here = Path(__file__).resolve()
    root = here.parents[3].parent  # .../.softhouse/capture/t326-.../instruments/ -> repo root
    pin = Path(args.pin) if args.pin else root / ".softhouse/guards/dead-path-frontier.pin"

    body = HEADER + "\n".join(rows_from(Path(args.census))) + "\n"

    if args.check:
        if not pin.exists():
            print("DIFFERS: %s does not exist" % pin)
            return 1
        if pin.read_text() == body:
            print("IDENTICAL: %s matches the derived content" % pin)
            return 0
        print("DIFFERS: %s does not match the derived content" % pin)
        return 1

    pin.parent.mkdir(parents=True, exist_ok=True)
    pin.write_text(body)
    print("wrote %d row(s) to %s" % (body.count("\n") - HEADER.count("\n"), pin))
    return 0


if __name__ == "__main__":
    sys.exit(main())
