#!/bin/sh
# T327 -- THE WHOLE THROWAWAY CAPTURE, END TO END, AS ONE REPRODUCIBLE COMMAND.
#
#   bash run-all.sh
#
# ADAPTED FROM T305's run-all.sh, WITH ONE DELIBERATE DIFFERENCE THAT IS RECORDED RATHER THAN
# QUIETLY MADE: T305's version opens with
#     rm -rf "$OUT" "$DIR/req"
# and this one DOES NOT delete `req/`. T327's request bodies are generated by capture.sh into
# req/ during the run, exactly as T305's were, but the guard here refuses a non-empty out/ instead
# of clearing it, so re-running cannot silently overwrite an accepting capture whose instance no
# longer exists. Same reason T305's rig was copied rather than re-run in place: running T305's
# run-all.sh in the merged tree would have deleted T305's committed out/.
#
# WHY THIS EXISTS. The admissibility argument for a capture taken on an instance that no longer
# exists rests on the RECIPE being deterministic and committed. A reviewer who wants to re-derive
# any byte in out/ runs this one script. What it CANNOT reproduce is a transaction id (Fineract
# generates one per POST), a wall-clock timestamp, and THE DATES -- because the dates are computed
# relative to the business date, which is today in Asia/Ulaanbaatar on the day it runs. That is a
# feature: the vector this capture will feed asserts a RELATION between transaction date, closing
# date and business date, which no calendar can falsify (T289's date strategy (c)).
#
# ORDER, AND EVERY STEP IS FAIL-CLOSED:
#   0  guard-throwaway-isolation.sh  -- refuses unless the rig cannot touch the standing stack,
#                                       and records the standing baseline the later steps re-check
#   1  docker compose up             -- fresh containers, no named volume, port 8444
#   2  wait for the health endpoint
#   3  setup.sh                      -- MNT, three GL accounts
#   4  capture.sh                    -- B-2 (accept on the business date + control) and
#                                       B-1 (closure, two refusal controls, accept at D+1)
#   5  down.sh                       -- destroy, and prove the standing oracle did not move
set -eu
DIR=$(cd "$(dirname "$0")" && pwd)
CF="$DIR/docker-compose.t327.yml"
OUT="$DIR/out"
say() { printf '\n=== %s\n' "$*"; }

if [ -d "$OUT" ] && [ -n "$(ls -A "$OUT" 2>/dev/null || true)" ]; then
  if [ "${T327_FORCE_OVERWRITE:-0}" != "1" ]; then
    echo "REFUSE: $OUT is not empty. An accepting capture's bytes are irreplaceable -- the instance"
    echo "        that produced them is destroyed. Move them aside, or set T327_FORCE_OVERWRITE=1"
    echo "        if you genuinely mean to discard them."
    exit 1
  fi
  rm -rf "$OUT"
fi
mkdir -p "$OUT" "$DIR/req" /tmp/t327-oracle-logs

say "0 isolation guard (also records out/STANDING-baseline.txt)"
bash "$DIR/guard-throwaway-isolation.sh" > "$OUT/STANDING-baseline.txt" 2>&1 || {
  cat "$OUT/STANDING-baseline.txt"; echo "REFUSED at step 0."; exit 1; }
cat "$OUT/STANDING-baseline.txt"

say "1 docker compose up"
docker compose -p t327-oracle -f "$CF" up -d 2>&1 | sed 's/^/  /'

say "2 waiting for https://localhost:8444/fineract-provider/actuator/health"
i=0
while [ "$i" -lt 60 ]; do
  if curl -sk -m 5 -o /dev/null https://localhost:8444/fineract-provider/actuator/health 2>/dev/null; then break; fi
  i=$((i + 1)); sleep 10
done
curl -sk https://localhost:8444/fineract-provider/actuator/health | tee "$OUT/THROWAWAY-health.txt"; printf '\n'
grep -q '"status":"UP"' "$OUT/THROWAWAY-health.txt" || { echo "throwaway never came up"; exit 1; }

say "3 setup.sh"
bash "$DIR/setup.sh" 2>&1 | tee "$OUT/SETUP.txt"

say "4 capture.sh -- B-2 AND B-1"
bash "$DIR/capture.sh" 2>&1 | tee "$OUT/CAPTURE.txt"

say "5 down.sh -- destroy and prove the standing oracle did not move"
bash "$DIR/down.sh" 2>&1 | tee "$OUT/TEARDOWN.txt"

say "manifest"
bash "$DIR/manifest.sh"
