#!/usr/bin/env python3
"""mapgen.py [--root <worktree>] [<context> ...] — write .softhouse/maps/<context>.md

WHY (F-2026-09-10-navigation-is-the-dominant-failure; the 2026-09-11 progress review):
64% of agent actions across 71 runs were grep/find/cat, and OH-WOJE-AA spent 422 events
searching for a file the driver found in two minutes. A brief that says "see the map"
removes the search.

The map is GENERATED from the tree, never hand-written, so it cannot rot the way the
hand-written NOT-GRADED bullets did (A2-34 F-4/F-5). Regenerate after every merge that
touches a context; a stale map is worse than none.

Every line is derived: seams from the capabilities file, vectors and their capture_ref from
the vector files, drives from RegisterWrong call sites (file:line), port functions from
`func` declarations in non-test, non-conformance files, captures from every capture_ref and
every capture directory's OWNER.md. Nothing is summarised by a person.
"""
import glob, json, os, re, subprocess, sys

args = sys.argv[1:]
root = "."
if args[:1] == ["--root"]:
    root, args = args[1], args[2:]
os.chdir(root)
APPS = "nexus/internal/apps"
ctxs = args or sorted(d for d in os.listdir(APPS) if os.path.isdir(f"{APPS}/{d}/conformance"))
os.makedirs(".softhouse/maps", exist_ok=True)

def rel(p): return os.path.relpath(p)
FUNC_RE = re.compile(r"^func (\([^)]*\) )?")

owners = {}
for o in glob.glob(".softhouse/capture/*/OWNER.md"):
    first = next((l.strip("# \n") for l in open(o, errors="replace") if l.strip()), "")
    owners[os.path.dirname(o)] = first[:140]

for ctx in ctxs:
    out = []
    w = out.append
    w(f"# MAP — `{ctx}`  (GENERATED by `.softhouse/briefs/tools/mapgen.py` — do not edit; regenerate)\n")
    w("Use this instead of searching. If something you need is not here, say so in your report —")
    w("that is a defect in the map, and the driver fixes the generator.\n")

    capf = next((f for f in (f".softhouse/capabilities-{ctx}.json", f".softhouse/vectors/capabilities-{ctx}.json") if os.path.exists(f)), None)
    w("## Seams and capabilities")
    if capf:
        d = json.load(open(capf))
        w(f"Source: `{capf}`\n")
        for s in d.get("seams", []):
            w(f"* seam **{s.get('name')}** — {str(s.get('description',''))[:160]}")
        for c in d.get("capabilities", []):
            g = c.get("in_graded_domain")
            w(f"* capability `{c.get('name')}` — in_graded_domain: **{g}** — {str(c.get('description',''))[:120]}")
    else:
        w("(no capabilities file)")

    w("\n## Vectors (what is graded today)")
    vecs = sorted(glob.glob(f".softhouse/vectors/{ctx}/*.json"))
    w(f"{len(vecs)} files in `.softhouse/vectors/{ctx}/`\n")
    caps_used = {}
    for v in vecs:
        try: d = json.load(open(v))
        except Exception as e: w(f"* `{os.path.basename(v)}` — UNREADABLE ({e})"); continue
        p = d.get("provenance") or {}
        ref = p.get("capture_ref") or ""
        if ref: caps_used.setdefault(os.path.dirname(ref.split("/out/")[0] + "/x"), []).append(os.path.basename(v))
        top = ",".join(k for k in (d.get("request") or {}).keys())
        w(f"* `{os.path.basename(v)}` — request `{top}` — capture `{ref or '(none)'}`")

    w("\n## Registration — where to add a seam / implementation / drive")
    impl = f"{APPS}/{ctx}/conformance/impl.go"
    conf = sorted(glob.glob(f"{APPS}/{ctx}/conformance/**/*.go", recursive=True))
    for f in conf:
        for i, l in enumerate(open(f), 1):
            if re.match(r"func (Register|RegisterWrong)\(", l) or re.search(r"\bRegister\(\"[a-z0-9-]+-go\"", l):
                w(f"* `{rel(f)}:{i}` — `{l.strip()[:100]}`")
    w(f"* conformance package files: " + ", ".join(f"`{os.path.basename(f)}`" for f in conf if not f.endswith("_test.go")))
    cst = f"{APPS}/{ctx}/conformance/committed_store_test.go"
    w(f"* committed-store test (the only valid coverage instrument): " + (f"`{cst}`" if os.path.exists(cst) else "**ABSENT — coverage from conformance is NOT meaningful for this context**"))

    w("\n## Drives registered (name — file:line)")
    where = {}
    for f in conf:
        for i, l in enumerate(open(f), 1):
            m = re.search(r'RegisterWrong\("([a-z0-9-]+)"', l)
            if m and not l.lstrip().startswith(("func", "//")):
                where.setdefault(m.group(1), f"{rel(f)}:{i}")
    names, src = None, "source grep (binary unavailable)"
    binp = f"./internal/apps/{ctx}/conformance/cmd/conformance"
    if os.path.isdir(f"nexus/{binp[2:]}"):
        cmd = ["go", "run", binp] + ([] if ctx == "loanschedule" else ["-root", os.getcwd()]) + ["-list-implementations"]
        try:
            r = subprocess.run(cmd, cwd="nexus", capture_output=True, text=True, timeout=300)
            got = [l.split()[0] for l in r.stdout.splitlines() if l.strip()]
            if r.returncode == 0 and got:
                names, src = [g for g in got if "-wrong-" in g], "the binary's own -list-implementations"
        except Exception:
            pass
    if names is None:
        names = sorted(where)
    w(f"Source: {src}.\n")
    for d in names:
        w(f"* `{d}` — " + (f"`{where[d]}`" if d in where else "(registered through a table, not a literal call — see the context's wrong-drive table)"))
    n = len(names)
    w(f"\n{n} drives.")

    w("\n## Port functions (non-test, non-conformance)")
    for f in sorted(glob.glob(f"{APPS}/{ctx}/*.go")):
        if f.endswith("_test.go"): continue
        fns = [(i, l) for i, l in enumerate(open(f), 1) if l.startswith("func ")]
        if not fns: continue
        names = [f"`{FUNC_RE.sub('', l).split('(')[0]}`:{i}" for i, l in fns[:40]]
        w(f"* `{rel(f)}`: " + ", ".join(names) + (" …" if len(fns) > 40 else ""))

    w("\n## Captures this context's vectors already cite")
    for c, vs in sorted(caps_used.items()):
        w(f"* `{c}/` — {len(vs)} vector(s) — {owners.get(c, '(no OWNER.md)')}")
    w("\n## Every capture directory (with its OWNER.md title) — check the instance before using one")
    w("`tierA-a2/` and other early `t*`/`A2-*` captures came from an EARLIER oracle instance: their ids name")
    w("different rows on today's tenant. Prefer captures whose OWNER.md names tenant `gerege` on `gerege-oracle-db`.\n")
    for c in sorted(owners):
        w(f"* `{c}/` — {owners[c]}")

    w("\n## Measuring (flags are per-binary — use the tools, never the binary by hand)")
    if os.path.isdir(f"{APPS}/{ctx}/conformance/cmd/conformance"):
        w(f"    bash .softhouse/briefs/tools/kills.sh {ctx} <impl> <worktree>      # kill count of one drive")
        w(f"    bash .softhouse/briefs/tools/capcount.sh <worktree> {ctx} {ctx}-go   # vectors the reference FAILS (want 0)")
        w(f"    bash .softhouse/briefs/tools/redcount.sh <worktree> {ctx}            # drives that kill")
    else:
        w(f"    `{ctx}` has NO cmd/conformance binary: its drives are measured by the CENSUS block of")
        w(f"    `bash .softhouse/conformance.sh`. kills.sh fails loudly here — that is NOT a zero.")
    w(f"    go test -count=1 -coverpkg=./internal/apps/{ctx} -coverprofile=/tmp/c.cov ./internal/apps/{ctx}/conformance/...   # from nexus/")
    w("    Controls: loanschedule-wrong-days-in-year-365 = 45, loanschedule-wrong-half-even = 5,")
    w("              parties-wrong-iota-ordinals = 12, charges-wrong-rounding-half-even = 1")
    w("\n## The oracle, if a brief allows it")
    w("REST `https://localhost:8443/fineract-provider/api/v1` (`curl -k -u mifos:password -H 'Fineract-Platform-TenantId: gerege'`).")
    w("SQL read-only: `docker exec gerege-oracle-db psql -U postgres -d fineract_gerege -At -c '…'` — NOT `fineract-db-1` (stale).")
    w("Pinned Fineract source: `/Users/buv/fineract` @ `426a23544` (read-only).")

    path = f".softhouse/maps/{ctx}.md"
    open(path, "w").write("\n".join(out) + "\n")
    print(f"{path}: {len(vecs)} vectors, {n} drives")
