#!/bin/sh
# T352. Digest every artefact in this capture directory, so a later edit to any of
# them is detectable. Same purpose as tierA-a2/MANIFEST.sha256, generated by shell
# rather than by python because nothing here needs to parse a number and a rig that
# never parses a number cannot round-trip one through a binary double (P-25).
set -eu
DIR=$(cd "$(dirname "$0")" && pwd)
cd "$DIR"
find . -type f \
     ! -name 'MANIFEST.sha256' \
     ! -name '.DS_Store' \
     | LC_ALL=C sort \
     | while IFS= read -r f; do
         if command -v shasum >/dev/null 2>&1; then
           shasum -a 256 "$f"
         else
           sha256sum "$f"
         fi
       done > MANIFEST.sha256
printf '%s entries\n' "$(wc -l < MANIFEST.sha256 | tr -d ' ')"
