#!/usr/bin/env python3
"""T401 -- the exact rows `10-regen-pin.py` would ADD if selector S2 is widened to `.zsh`.

THIS IS NOT A REPLACEMENT PIN AND MUST NEVER BE PASTED INTO ONE. P-83: the pin is
regenerated BY RUNNING `.softhouse/capture/t326-frontier-host-state/instruments/10-regen-pin.py`
against the widened census, never by arithmetic and never by transcription. What this
prints is the COST STATEMENT that belongs in the request -- "here is exactly what the
regeneration will produce, so the reviewer can judge the +7 before it lands" -- and it is
derived by set difference over two census transcripts, both of which are committed beside it.

A '-' row would be a row the widening DROPPED. Widening a selector may only ADD, so a
non-empty removal set means the patch did something other than widen, and the report says
so rather than printing the addition set alone.
"""
import re
import sys

BASE = ".softhouse/capture/t401-zsh-census-gap/evidence/21-deadpath-BASE.txt"
ZSH = ".softhouse/capture/t401-zsh-census-gap/evidence/23-deadpath-ZSH.txt"


def rows(path):
    """(file, literal) pairs, in the pin's own `FILE | LITERAL` spelling."""
    out = []
    cur = None
    try:
        fh = open(path)
    except OSError as e:
        # FAIL CLOSED. An unreadable transcript is not an empty diff.
        print("T401 ABORT (2): cannot read %s: %s" % (path, e), file=sys.stderr)
        raise SystemExit(2)
    with fh:
        for line in fh:
            m = re.match(r"^  (\.softhouse/\S+)$", line.rstrip())
            if m:
                cur = m.group(1)
                continue
            m = re.match(r"^      -> (\S+)$", line.rstrip())
            if m and cur:
                out.append("%s | %s" % (cur, m.group(1)))
    if not out:
        print("T401 ABORT (2): parsed ZERO rows from %s. A parser that reads nothing "
              "reports 'no change' (P-35). REFUSED." % path, file=sys.stderr)
        raise SystemExit(2)
    return out


b = rows(BASE)
z = rows(ZSH)
added = [r for r in z if r not in b]
removed = [r for r in b if r not in z]

print("T401 -- THE EXACT ROWS `10-regen-pin.py` WOULD ADD IF S2 IS WIDENED TO .zsh")
print("source : %s" % BASE)
print("         %s" % ZSH)
print("base rows %d   +zsh rows %d   ADDED %d   REMOVED %d"
      % (len(b), len(z), len(added), len(removed)))
print()
print("ADDED (pin format: FILE | LITERAL):")
for r in sorted(added):
    print("  " + r)
print()
print("REMOVED (must be empty -- a widening may only add):")
for r in sorted(removed):
    print("  " + r)
if not removed:
    print("  (none)")
raise SystemExit(0 if not removed else 1)
