#!/usr/bin/env bash
# T367 -- INDEPENDENT re-drive of T363's instrument. READ-ONLY: it only runs T363's script,
# which issues nothing but SELECTs. No probe is fired by this file.
#
#   bash .softhouse/reviews/t367-review-t363/drive.sh
#
# Every drive below is regenerated by the reviewer. P-22: do not accept a transcript.
set -uo pipefail
D=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OUT="$D/out"
UT="$D/t363-under-test"
mkdir -p "$OUT" "$UT/instruments"

# BOOTSTRAP -- the artefact under test is extracted FROM THE BRANCH, never from disk, so this
# drive cannot silently grade a merged-and-since-edited copy. T363's own files are not
# duplicated into this review's commit; they are re-extracted on every run.
B=softhouse/T363-oracle-baseline
P=.softhouse/capture/t363-oracle-baseline
git -C "$(git rev-parse --show-toplevel)" show "$B:$P/instruments/oracle-state-baseline.sh" > "$UT/instruments/oracle-state-baseline.sh" || exit 2
git -C "$(git rev-parse --show-toplevel)" show "$B:$P/PROBES.tsv"                          > "$UT/PROBES.tsv"                          || exit 2
I="$UT/instruments/oracle-state-baseline.sh"

run() { # run <name> <expected-exit> <env-assignments...> --  <interpreter>
  local name=$1 want=$2; shift 2
  ( "$@" ) > "$OUT/$name.txt" 2>&1
  local rc=$?
  if [ "$rc" -eq "$want" ]; then printf 'ok   %-28s exit %-2s (expected %s)\n' "$name" "$rc" "$want"
  else printf '***  %-28s exit %-2s EXPECTED %s -- DRIVE FAILED\n' "$name" "$rc" "$want"; FAIL=1; fi
}
FAIL=0

# --- GREEN: the registry as shipped -------------------------------------------------------
run DRIVE-GREEN 0 bash "$I"

# --- RED-4: ONE forgotten probe. The whole P-45 argument. ---------------------------------
grep -v 'T359' "$D/t363-under-test/PROBES.tsv" > "$OUT/reg-no-t359.tsv"
run DRIVE-RED4 1 env ORACLE_BASELINE_REGISTRY="$OUT/reg-no-t359.tsv" bash "$I"

# --- RED-1: floor present, every attribution row removed ----------------------------------
grep -E '^(floor|#)|^$' "$D/t363-under-test/PROBES.tsv" > "$OUT/reg-floor-only.tsv"
run DRIVE-RED1 1 env ORACLE_BASELINE_REGISTRY="$OUT/reg-floor-only.tsv" bash "$I"

# --- RED-1b: only the LEDGER rows forgotten (cmd rows kept) -------------------------------
grep -v $'^txn\t' "$D/t363-under-test/PROBES.tsv" > "$OUT/reg-no-txn.tsv"
run DRIVE-RED1b 1 env ORACLE_BASELINE_REGISTRY="$OUT/reg-no-txn.tsv" bash "$I"

# --- RED-2: database unreachable ----------------------------------------------------------
run DRIVE-RED2 2 env ORACLE_BASELINE_DB_CONTAINER=no-such-container-t367 bash "$I"

# --- RED-2b: container reachable, DATABASE name wrong -------------------------------------
run DRIVE-RED2b 2 env ORACLE_BASELINE_DB_NAME=no_such_db_t367 bash "$I"

# --- RED-5: registry missing entirely -----------------------------------------------------
run DRIVE-RED5 1 env ORACLE_BASELINE_REGISTRY="$OUT/does-not-exist.tsv" bash "$I"

# --- RED-6: registry present, floor line deleted (non-numeric floor) ----------------------
grep -v $'^floor\t' "$D/t363-under-test/PROBES.tsv" > "$OUT/reg-no-floor.tsv"
run DRIVE-RED6 1 env ORACLE_BASELINE_REGISTRY="$OUT/reg-no-floor.tsv" bash "$I"

# --- exit 3: the interpreter guard, on every shell this host has --------------------------
for sh_bin in /bin/sh /bin/dash /usr/bin/dash /bin/zsh /bin/ksh; do
  [ -x "$sh_bin" ] || continue
  n="DRIVE-INTERP-$(basename "$sh_bin")"
  run "$n" 3 "$sh_bin" "$I"
done

echo
if [ "$FAIL" -eq 0 ]; then echo "ALL DRIVES BEHAVED AS EXPECTED"; else echo "AT LEAST ONE DRIVE DID NOT"; fi
exit "$FAIL"
