#!/usr/bin/env bash
# T108 — capture the environment facts the ruling rests on.
#
# This is the part four previous workers did NOT record, and it is the whole
# reason they disagreed: on this host the token `grep` means two different
# programs depending on WHERE it is typed.
#
#   * typed into the Claude Code Bash tool  -> a SHELL FUNCTION from the
#     session shell snapshot, which re-execs the `claude` binary with
#     argv[0]=ugrep and a hard-coded `-I` (skip binary files).
#   * typed inside a script run as `sh x.sh` / `bash x.sh` -> /usr/bin/grep,
#     BSD grep 2.6.0-FreeBSD.  Shell functions are not exported to children.
#
# No arithmetic; no floating point (P-25).
#
# Usage: bash capture-env.sh          # writes out/env.txt, out/hexdumps.txt
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/out"
mkdir -p "$OUT"

{
  echo "T108 environment capture"
  echo "run at            $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "host              $(uname -a)"
  echo "macOS             $(sw_vers -productVersion 2>/dev/null) build $(sw_vers -buildVersion 2>/dev/null)"
  echo
  echo "--- ambient locale of the Claude Code Bash tool shell"
  locale
  echo
  echo "--- /usr/bin/grep"
  /usr/bin/grep --version 2>&1 | head -1
  echo
  echo "--- is there a standalone \`ugrep\` binary on this host?"
  echo "command -v ugrep -> [$(command -v ugrep 2>/dev/null)]"
  for d in /opt/homebrew /usr/local "$HOME/.local" "$HOME/bin" /pkg/env/global/bin; do
    if [ -d "$d" ]; then
      n=$(find "$d" -maxdepth 4 -name ugrep -type f 2>/dev/null | head -3)
      echo "  $d exists; ugrep found: [${n:-none}]"
    else
      echo "  $d DOES NOT EXIST"
    fi
  done
  echo
  echo "ANSWER: no standalone ugrep binary — T107b was right about that."
  echo "        ugrep is EMBEDDED IN THE \`claude\` EXECUTABLE and reached via argv[0]."
  echo
  echo "--- CLAUDE_CODE_EXECPATH"
  echo "CLAUDE_CODE_EXECPATH=[${CLAUDE_CODE_EXECPATH:-UNSET}]"
  echo
  echo "--- version reported when the claude binary is invoked as ugrep"
  ARGV0=ugrep "${CLAUDE_CODE_EXECPATH:-$HOME/.local/bin/claude}" --version 2>&1 | head -1
  echo
  echo "--- the shell snapshots on this host that define the \`grep\` function"
  ls -l "$HOME/.claude/shell-snapshots/" 2>/dev/null
  echo
  echo "  snapshots containing 'ARGV0=ugrep':"
  for s in "$HOME"/.claude/shell-snapshots/*.sh; do
    c=$(/usr/bin/grep -c 'ARGV0=ugrep' "$s" 2>/dev/null)
    echo "    $(basename "$s")  hits=$c  mtime=$(date -r "$s" -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null)"
  done
  echo
  echo "  NOTE: the snapshot dated before T80's fire carries the same function."
  echo "        T80's own session snapshot is not retained, so the inference that"
  echo "        T80 had it too is STRONG BUT NOT DIRECTLY OBSERVED. [UNVERIFIED]"
  echo
  echo "--- the exact bash diagnostic that poisoned T80's transcript"
  echo "    source line in pathb/t36/preconditions.sh (pre-fix, T85 F-2):"
  echo "      bad \"PostgreSQL version is '\$pgv', pin is '\$PIN_PG_MAJOR_MINOR…'\""
  echo "    the unbraced name runs into U+2026 (e2 80 a6); bash takes 0xe2 as"
  echo "    part of the identifier and, under set -u, dies.  Reproduced:"
  tmp="$(mktemp -t t108unb)"
  cat > "$tmp.sh" <<'EOS'
set -u
echo "pin is '$PIN_PG_MAJOR_MINOR…'"
EOS
  bash "$tmp.sh" > "$tmp.out" 2>&1
  echo "      exit=$?"
  echo "      bytes of the diagnostic:"
  xxd "$tmp.out" | sed 's/^/        /'
  echo
  echo "    -> a LONE 0xE2.  Invalid UTF-8, and it sits BEFORE the words"
  echo "       'unbound variable' on the same line.  That is the decisive detail."
  rm -f "$tmp" "$tmp.sh" "$tmp.out"
} > "$OUT/env.txt" 2>&1

# the grep shell function, verbatim
{
  echo "The Claude Code Bash-tool \`grep\` shell function, verbatim."
  echo "Source: \$HOME/.claude/shell-snapshots/<session>.sh (regenerated per session)."
  echo "Captured $(date -u +%Y-%m-%dT%H:%M:%SZ) from the snapshot in force for T108."
  echo
  newest=""
  for s in "$HOME"/.claude/shell-snapshots/*.sh; do
    if /usr/bin/grep -q 'ARGV0=ugrep' "$s"; then newest="$s"; fi
  done
  echo "=== $newest   (newest snapshot on this host that defines it)"
  echo
  sed -n '/^# Shadow find\/grep/,/^unalias grep/p' "$newest"
  sed -n '/^function grep {/,/^}/p' "$newest"
  echo
  echo "NOTE: \`find\` is shadowed the same way, onto an embedded \`bfs\`."
  echo
  echo "The three flags that decide this whole adjudication:"
  echo "  -G              basic regular expressions, grep compatibility mode"
  echo "  -I              SKIP FILES THAT LOOK BINARY  <-- the silent-miss cause"
  echo "  --ignore-files  obey .gitignore-style ignore files"
} > "$OUT/shell-function.txt" 2>&1

# hexdumps of every corpus file
{
  echo "T108 corpus — byte-exact hexdumps"
  echo "generated by gen-corpus.py; re-run it to rebuild these files verbatim"
  echo
  for f in "$HERE"/corpus/*.txt; do
    echo "=== $(basename "$f")   $(wc -c < "$f" | tr -d ' ') bytes   sha256 $(shasum -a 256 "$f" | cut -d' ' -f1)"
    xxd "$f"
    echo
  done
} > "$OUT/hexdumps.txt" 2>&1

echo "wrote $OUT/env.txt"
echo "wrote $OUT/shell-function.txt"
echo "wrote $OUT/hexdumps.txt"
