#!/usr/bin/env python3
"""
T46 / M-5 — generate `src/CaptureMathContext3.java` from `src/CaptureMathContext.java`.

The re-emission harness is GENERATED rather than hand-copied so that the diff against the
committed harness is mechanical and reviewable: this script makes exactly four edits and
asserts every anchor it depends on.  Run it, then `bash src/run-mathcontext3.sh`.

  (a) prepend a header
  (b) rename the class
  (c) relabel the payload's `harness` field
  (d) APPEND four keys per case, read off the `mc` object handed to `generate(mc, config)`
      -- the two original keys are left untouched, so every previously published value is
      still present and comparable leaf by leaf.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "src" / "CaptureMathContext.java"
DST = HERE.parent / "src" / "CaptureMathContext3.java"

HEADER = '''/*
 * T46 -- RE-EMISSION of T42's capture 1 with the THREADED MathContext ECHOED OFF THE OBJECT.
 *
 * GENERATED by analysis/t46_make_capture3.py from src/CaptureMathContext.java.  It is a
 * byte-for-byte copy of that file except for: this header, the class name, the payload's
 * "harness" label, and FOUR ADDITIONAL keys per case appended after the two existing ones --
 * nothing removed, nothing renamed, nothing re-ordered before them.
 *
 * WHY.  Audit finding M-5 (T44 section 3): CaptureMathContext.java:394-395 writes c.precision()
 * and c.mode() -- the case record's INTENT -- under keys named `threadedMathContextPrecision`
 * and `threadedMathContextRoundingMode`, which assert that they were read off the object.  That
 * breaks T42's own ratified attestation rule 2 ("on the THREADED context, echo the object, not
 * the intent") on the very capture that carries experiment E1, 214 of 354 cases.
 *
 * WHAT IS ADDED, read off `mc` -- the SAME reference passed to generator.generate(mc, config):
 *     "threadedMathContext"                       mc.toString()
 *     "threadedMathContextPrecisionFromObject"    mc.getPrecision()
 *     "threadedMathContextRoundingModeFromObject" mc.getRoundingMode()
 *     "wiring"                                    where mc came from, stated explicitly
 *
 * The arithmetic is untouched: same `mc` object, same shapes, same seam, same pinned image.  A
 * published capture may be RE-EMITTED, never mutated (.softhouse/patterns.md); if any previously
 * published cell moves, this re-emission is INADMISSIBLE and must not be published.
 * src/run-mathcontext3.sh enforces exactly that, leaf by leaf, before the payload is kept.
 *
 * ---- the original header follows, unmodified ----
 */
'''

OLD_KEYS = '''        b.append("        \\"threadedMathContextPrecision\\": ").append(c.precision()).append(",\\n");
        b.append("        \\"threadedMathContextRoundingMode\\": \\"").append(c.mode()).append("\\",\\n");'''

NEW_KEYS = OLD_KEYS + '''
        // ---- T46 / M-5: the same two readings taken OFF THE OBJECT handed to the callee ----
        // `mc` below is the very reference passed to generator.generate(mc, config).
        b.append("        \\"threadedMathContext\\": \\"").append(mc.toString()).append("\\",\\n");
        b.append("        \\"threadedMathContextPrecisionFromObject\\": ").append(mc.getPrecision()).append(",\\n");
        b.append("        \\"threadedMathContextRoundingModeFromObject\\": \\"").append(mc.getRoundingMode()).append("\\",\\n");
        b.append("        \\"wiring\\": \\"PATH_A -- this MathContext object was constructed by the harness ")
                .append("(new MathContext(case.precision, case.mode)) and is the first argument of ")
                .append("EmbeddableProgressiveLoanScheduleGenerator.generate(mc, config).  It is NOT sourced ")
                .append("from MoneyHelper.getMathContext().\\",\\n");'''

OLD_CLASS = "public class CaptureMathContext {"
NEW_CLASS = "public class CaptureMathContext3 {"

OLD_HARNESS = 'sb.append("  \\"harness\\": \\"CaptureMathContext.java\\",\\n");'
NEW_HARNESS = ('sb.append("  \\"harness\\": \\"CaptureMathContext3.java (T46 re-emission of '
               'CaptureMathContext.java with the threaded MathContext echoed off the object)\\",\\n");')


def main():
    src = SRC.read_text()
    for anchor in (OLD_KEYS, OLD_CLASS, OLD_HARNESS):
        if src.count(anchor) != 1:
            sys.exit("anchor not found exactly once: %r" % anchor[:60])
    out = HEADER + src
    out = out.replace(OLD_CLASS, NEW_CLASS, 1)
    out = out.replace(OLD_HARNESS, NEW_HARNESS, 1)
    out = out.replace(OLD_KEYS, NEW_KEYS, 1)
    DST.write_text(out)
    print("wrote %s (%d bytes, from %d)" % (DST, len(out), len(src)))
    print("edits: header + class rename + harness label + 4 appended keys")


if __name__ == "__main__":
    main()
