#!/usr/bin/env bash
# T196 — the whole evidence base for "apply T183's backstep fix to T179's classifier",
# regenerated by ONE command:
#
#     bash .softhouse/reviews/t41-probe/t196-drive.sh
#
# bash, never sh (a wrong interpreter must refuse, not half-run).
#
# SAFETY, and it is the point of this file's shape:
#   * NOT ONE SCRIPT FROM THE REVIEWED POPULATION IS EVER EXECUTED.  Every edit*.py
#     is an in-place rewriter of the RATIFIED DEC-1 and/or the FROZEN contract.go.
#     They are only ever COPIED into $(mktemp -d) and PARSED by the classifier.
#     T161 corrupted the live rig it was proving; this script cannot, because it
#     never invokes a population script and never writes inside the repository.
#   * The four constructed fixtures name `docs/adr/DEC-1-...` as their target,
#     because that is what makes them valid fixtures.  They are stored as `.py.txt`
#     in `t196-fixtures-INERT/` — no `.py` sweep enumerates them and no shell runs
#     them — and are copied to scratch under a `.py` name only for the duration.
#   * Both frozen digests are printed at the TOP and the BOTTOM of every run, so the
#     transcript carries its own proof that neither artefact moved.
#
# P-57: no `| grep -q` and no `| head` anywhere below.  Under `pipefail` a closing
# reader turns SIGPIPE into a non-zero status that reads as a real failure, so every
# grep here takes a FILE argument and every truncation is `sed -n`.
# P-58: `grep` on this host is a shell FUNCTION that re-execs an embedded ugrep with
# `-I` and `--ignore-files`.  Everything below calls /usr/bin/grep (BSD grep 2.6.0-
# FreeBSD) BY ABSOLUTE PATH, so the program being measured is named, not inherited.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
DEC1="$REPO/docs/adr/DEC-1-schedule-generator-adapter.md"
CGO="$REPO/nexus/internal/apps/loanschedule/contract/contract.go"
FIX="$REPO/.softhouse/reviews/t41-probe/t196-fixtures-INERT"
LIVE="$REPO/.softhouse/reviews/t179-guard-classifier/guard_classify.py"
PATCH="$REPO/.softhouse/reviews/T183-evidence/PROPOSED-backstep.patch"
# The pre-T187 bytes of the population.  T187 hardened all 25 rewriters, so the
# shape D-1 is about no longer exists at today's main; the defect is still real and
# is driven against the bytes that had it.  16d5252 is the dispatch commit T187
# itself pinned its prefix census to.
PREFIX_REF="16d5252"

for f in "$DEC1" "$CGO" "$FIX" "$LIVE" "$PATCH"; do
  if [[ ! -e "$f" ]]; then
    echo "STOP: missing artefact: $f" >&2
    exit 3
  fi
done

SB="$(mktemp -d "${TMPDIR:-/tmp}/t196.XXXXXX")"
trap 'rm -rf "$SB"' EXIT

digests() {
  echo "  DEC-1       $(shasum -a 256 "$DEC1" | cut -d" " -f1)"
  echo "  contract.go $(shasum -a 256 "$CGO"  | cut -d" " -f1)"
}

echo "=============================================================================="
echo "T196 drive — frozen digests BEFORE"
digests
echo "  scratch: $SB"
echo "=============================================================================="

# --- the three classifier builds under comparison -----------------------------
# BASE  : T179 exactly as merged on main (the merge base of this branch).
# T183  : BASE + PROPOSED-backstep.patch, applied verbatim, unmodified.
# T196  : the live file on this branch.
MB="$(git -C "$REPO" merge-base HEAD main)"
git -C "$REPO" show "$MB:.softhouse/reviews/t179-guard-classifier/guard_classify.py" > "$SB/gc_base.py"
cp "$SB/gc_base.py" "$SB/gc_t183.py"
( cd "$SB" && patch -s -p0 gc_t183.py < "$PATCH" )
cp "$LIVE" "$SB/gc_t196.py"
echo
echo "classifier builds: BASE=$MB  T183=BASE+PROPOSED-backstep.patch  T196=working tree"
echo "python: $(python3 -V 2>&1)"
echo "grep measured with: /usr/bin/grep -> $(/usr/bin/grep --version 2>&1 | sed -n 1p)"

run() {  # run <build> <root> <label>; prints exit code, never dies
  local build="$1" root="$2" label="$3"
  python3 "$SB/$build.py" --root "$root" --enforce > "$SB/$label.txt" 2>&1
  echo "$?"
}

# --- PROBE A — D-1.  The fail-open, and its closure. --------------------------
echo
echo "=== PROBE A (D-1) — three rewriters whose write target is a PARAMETER"
mkdir -p "$SB/A"
for f in edit18 edit20 edit21; do
  git -C "$REPO" show "$PREFIX_REF:.softhouse/reviews/t41-probe/$f.py" > "$SB/A/$f.py"
done
echo "  fixtures: pre-T187 bytes of edit18/20/21 at $PREFIX_REF (COPIED, never run)"
echo "  BASE --enforce exit = $(run gc_base "$SB/A" A-base)   <-- 0 is the FAIL-OPEN"
echo "  T183 --enforce exit = $(run gc_t183 "$SB/A" A-t183)"
echo "  T196 --enforce exit = $(run gc_t196 "$SB/A" A-t196)"
echo "  --- BASE saw:"
sed -n '/COULD NOT BE RESOLVED/,/^$/p' "$SB/A-base.txt"
echo "  --- T196 sees:"
sed -n '/UNGUARDED MUTATIONS OF A TRUSTED/,/^$/p' "$SB/A-t196.txt"

# --- PROBE B — the fail-open inside T183's own patch --------------------------
echo
echo "=== PROBE B — one harmless call site must not launder a gate bypass"
mkdir -p "$SB/B"
cp "$FIX/red_union_scratch_mask.py.txt" "$SB/B/red_union_scratch_mask.py"
echo "  BASE --enforce exit = $(run gc_base "$SB/B" B-base)   (UNKNOWN: printed, not excused)"
echo "  T183 --enforce exit = $(run gc_t183 "$SB/B" B-t183)   <-- 0, and SILENTLY excused"
echo "  T196 --enforce exit = $(run gc_t196 "$SB/B" B-t196)"
echo "  --- T183 verdict matrix (the site is SCRATCH/SANDBOX, in neither finding list):"
sed -n '/scope x verdict/,/^  ALL /p' "$SB/B-t183.txt"
echo "  --- T196 sees:"
sed -n '/UNGUARDED MUTATIONS OF A TRUSTED/,/^$/p' "$SB/B-t196.txt"

# --- PROBE C — D-3 GREEN.  The shared-guard idiom must stop being punished. ---
echo
echo "=== PROBE C (D-3 GREEN) — mutation local, guard IMPORTED"
mkdir -p "$SB/C"
cp "$FIX/mylib_guard.py.txt"           "$SB/C/mylib_guard.py"
cp "$FIX/green_imported_cm.py.txt"     "$SB/C/green_imported_cm.py"
cp "$FIX/green_imported_atexit.py.txt" "$SB/C/green_imported_atexit.py"
echo "  BASE --enforce exit = $(run gc_base "$SB/C" C-base)   <-- 1: punishes the hardening idiom"
echo "  T196 --enforce exit = $(run gc_t196 "$SB/C" C-t196)"
echo "  --- BASE called these UNGUARDED:"
sed -n '/UNGUARDED MUTATIONS OF A TRUSTED/,/^$/p' "$SB/C-base.txt"
echo "  --- T196 import-hop disclosure:"
sed -n '/ONE IMPORT HOP/,/^$/p' "$SB/C-t196.txt"

# --- PROBE D — D-3 RED.  Following an import must not become a rubber stamp. --
echo
echo "=== PROBE D (D-3 RED) — an import that does NOT protect the site"
mkdir -p "$SB/D"
cp "$FIX/mylib_guard.py.txt"             "$SB/D/mylib_guard.py"
cp "$FIX/red_import_not_covered.py.txt"  "$SB/D/red_import_not_covered.py"
cp "$FIX/red_dead_registrar.py.txt"      "$SB/D/red_dead_registrar.py"
echo "  BASE --enforce exit = $(run gc_base "$SB/D" D-base)"
echo "  T196 --enforce exit = $(run gc_t196 "$SB/D" D-t196)   <-- MUST be 1"
sed -n '/UNGUARDED MUTATIONS OF A TRUSTED/,/^$/p' "$SB/D-t196.txt"

# --- PROBE E — the population, re-derived from the pre-fix bytes --------------
echo
echo "=== PROBE E — the contested population, re-derived at $PREFIX_REF"
mkdir -p "$SB/E"
git -C "$REPO" archive "$PREFIX_REF" .softhouse/reviews/t41-probe > "$SB/e.tar"
tar -xf "$SB/e.tar" -C "$SB/E"
EROOT="$SB/E/.softhouse/reviews/t41-probe"
python3 "$SB/gc_base.py" --root "$EROOT" --json "$SB/E-base.json" > "$SB/E-base.txt" 2>&1
echo "  BASE exit=$?"
python3 "$SB/gc_t196.py" --root "$EROOT" --json "$SB/E-t196.json" > "$SB/E-t196.txt" 2>&1
echo "  T196 exit=$?"
cat > "$SB/pop.py" <<'PYEOF'
import json, sys
d = json.load(open(sys.argv[1]))
adr, go, n = set(), set(), 0
for r in d:
    for s in r["sites"]:
        if s["scope"] != "TRUSTED":
            continue
        v = s["verb"]
        trunc = (v.startswith(("open(", "io.open(", "codecs.open(")) and "w" in v) \
            or v.startswith(("Path.write_text", "Path.write_bytes"))
        if not trunc:
            continue
        n += 1
        if "ADR" in s["target_tags"]:
            adr.add(r["path"])
        if "PORT" in s["target_tags"] or "RIG" in s["target_tags"]:
            go.add(r["path"])
print("    truncating write sites on a TRUSTED target : %d" % n)
print("    files -> RATIFIED DEC-1                    : %d" % len(adr))
print("    files -> FROZEN contract.go                : %d" % len(go))
print("    files -> BOTH                              : %d  %s"
      % (len(adr & go), sorted(adr & go)))
print("    distinct member FILES                      : %d" % len(adr | go))
print("    file-artefact PAIRS                        : %d" % (len(adr) + len(go)))
PYEOF
echo "  --- BASE (T179 as merged; its published F-2 figure was 22 = 17 ADR + 5 go):"
python3 "$SB/pop.py" "$SB/E-base.json"
echo "  --- T196 (settled answer is 25 files, 20 ADR + 7 go, 2 both):"
python3 "$SB/pop.py" "$SB/E-t196.json"

# --- PROBE F — today's main.  T187's hardening must survive the sharper tool. -
echo
echo "=== PROBE F — t41-probe at today's main, under the STRENGTHENED classifier"
echo "  T196 --enforce exit = $(run gc_t196 "$REPO/.softhouse/reviews/t41-probe" F-t196)"
sed -n '/mutation call sites/,/^  ALL /p' "$SB/F-t196.txt"
echo "  files present in t41-probe then vs now (rewriters added/removed since $PREFIX_REF):"
git -C "$REPO" ls-tree --name-only "$PREFIX_REF" .softhouse/reviews/t41-probe/ > "$SB/f-then.txt"
git -C "$REPO" ls-tree --name-only HEAD .softhouse/reviews/t41-probe/ > "$SB/f-now.txt"
diff "$SB/f-then.txt" "$SB/f-now.txt" > "$SB/f-diff.txt"
if /usr/bin/grep -c '^<' "$SB/f-diff.txt" > /dev/null 2>&1; then
  echo "    REMOVED since $PREFIX_REF:"; /usr/bin/grep '^<' "$SB/f-diff.txt"
else
  echo "    REMOVED since $PREFIX_REF: none"
fi
echo "    ADDED since $PREFIX_REF (T187's own instruments and transcripts):"
/usr/bin/grep '^>' "$SB/f-diff.txt" || echo "    none"

# --- PROBE G — the instrument's own selftest, including under -O --------------
echo
echo "=== PROBE G — T179's selftest against the MODIFIED classifier (P-56)"
python3 "$REPO/.softhouse/reviews/t179-guard-classifier/selftest.py" > "$SB/G.txt" 2>&1
echo "  selftest exit          = $?"
python3 -O "$REPO/.softhouse/reviews/t179-guard-classifier/selftest.py" > "$SB/G-O.txt" 2>&1
echo "  selftest exit under -O = $?"
sed -n '$p' "$SB/G.txt"
echo "  classifier on ITSELF (must stay ATOMIC, must self-flag in its own P-48 detector):"
python3 "$SB/gc_t196.py" --file "$LIVE" > "$SB/G-self.txt" 2>&1
sed -n '/P-48 DETECTOR/,/^$/p' "$SB/G-self.txt"


# --- PROBE H — every site this change moves, repo-wide, named ----------------
# This is the adjudication surface.  T183 declined to merge its own patch because
# five of its repo-wide reclassifications were unadjudicated; the only way to
# adjudicate them is to print them, individually, at TODAY's tree.  ~3 minutes.
echo
echo "=== PROBE H — repo-wide delta over .softhouse, site by site"
python3 "$SB/gc_base.py" --root "$REPO/.softhouse" --json "$SB/H-base.json" > "$SB/H-base.txt" 2>&1
echo "  BASE sweep exit=$?"
python3 "$SB/gc_t183.py" --root "$REPO/.softhouse" --json "$SB/H-t183.json" > "$SB/H-t183.txt" 2>&1
echo "  T183 sweep exit=$?"
python3 "$SB/gc_t196.py" --root "$REPO/.softhouse" --json "$SB/H-t196.json" > "$SB/H-t196.txt" 2>&1
echo "  T196 sweep exit=$?"
cat > "$SB/delta.py" <<'PYEOF'
import json, sys


def load(p):
    out = {}
    for r in json.load(open(p)):
        for s in r["sites"]:
            out[(r["path"], s["line"], s["verb"])] = s
    return out


a, b = load(sys.argv[1]), load(sys.argv[2])
new, lost = sorted(set(b) - set(a)), sorted(set(a) - set(b))
print("  sites: %d -> %d   (+%d new, -%d lost)" % (len(a), len(b), len(new), len(lost)))
for k in new:
    s = b[k]
    print("    NEW  %s:%d %s -> %s/%s tags=%s"
          % (k[0], k[1], k[2], s["scope"], s["verdict"], s["target_tags"]))
for k in lost:
    print("    LOST %s:%d %s" % k)
n = 0
for k in sorted(set(a) & set(b)):
    # tags compared too: a site reaching the right SCOPE via the wrong TAG is the
    # right answer for the wrong reason, and that is exactly what T196 corrected on
    # the four *-promote-vectors.py writes (CAPTURE -> STORE).
    if a[k]["scope"] == b[k]["scope"] and a[k]["verdict"] == b[k]["verdict"] \
            and a[k]["target_tags"] == b[k]["target_tags"]:
        continue
    n += 1
    print("    MOVED %s:%d %s" % k)
    print("          %s/%s tags=%s   ->   %s/%s tags=%s"
          % (a[k]["scope"], a[k]["verdict"], a[k]["target_tags"],
             b[k]["scope"], b[k]["verdict"], b[k]["target_tags"]))
    print("          target: %s" % b[k]["target"][:100])
print("  reclassified: %d" % n)
PYEOF
echo "  --- BASE -> T183 (the patch exactly as T183 wrote it):"
python3 "$SB/delta.py" "$SB/H-base.json" "$SB/H-t183.json"
echo "  --- BASE -> T196 (what this branch actually merges):"
python3 "$SB/delta.py" "$SB/H-base.json" "$SB/H-t196.json"
echo "  --- T183 -> T196 (what T196 changed about T183's patch):"
python3 "$SB/delta.py" "$SB/H-t183.json" "$SB/H-t196.json"
echo "  --- T196 import-hop disclosure over the whole of .softhouse:"
sed -n '/ONE IMPORT HOP/,/^$/p' "$SB/H-t196.txt"

echo
echo "=============================================================================="
echo "T196 drive — frozen digests AFTER"
digests
echo "=============================================================================="
